"""
Context compaction — summarises older turns to keep the active context
window below the model's practical limit while retaining key facts.

Why this exists: a long agentic session accumulates many tool call /
tool result pairs. Past a certain point, old content wastes tokens and
can even degrade reasoning. Compaction runs when the message count
crosses a threshold, replacing the oldest messages with a summary.

The summary is generated by the same model doing the reasoning, injected
as a single human message: "Summary of prior conversation: ...".
Subsequent turns see the summary plus the recent N messages — enough to
maintain coherence without the full history.
"""

from __future__ import annotations

import os
from typing import Any

from langchain_aws import ChatBedrockConverse
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage

MODEL_ID = os.getenv("BEDROCK_MODEL_ID", "anthropic.claude-3-5-sonnet-20241022-v2:0")
REGION = os.getenv("AWS_DEFAULT_REGION", "eu-west-2")

# Compact when the message list exceeds this length.
COMPACT_AFTER = int(os.getenv("CONTEXT_COMPACT_AFTER", "40"))
# Keep this many recent messages verbatim after compaction.
KEEP_RECENT = int(os.getenv("CONTEXT_KEEP_RECENT", "10"))


def maybe_compact(messages: list[BaseMessage]) -> list[BaseMessage]:
    """
    If *messages* is longer than COMPACT_AFTER, summarise everything except
    the most recent KEEP_RECENT messages and return the compacted list.
    Otherwise return *messages* unchanged.
    """
    if len(messages) <= COMPACT_AFTER:
        return messages

    to_summarise = messages[:-KEEP_RECENT]
    recent = messages[-KEEP_RECENT:]

    summary = _summarise(to_summarise)
    return [HumanMessage(content=f"[Summary of prior conversation]\n{summary}")] + recent


def _summarise(messages: list[BaseMessage]) -> str:
    llm = ChatBedrockConverse(model=MODEL_ID, region_name=REGION)
    prompt = [
        SystemMessage(content=(
            "Summarise the following conversation history concisely. "
            "Preserve all key facts, decisions, and findings the agent has made. "
            "Output plain text, no headers."
        )),
        *messages,
    ]
    response = llm.invoke(prompt)
    return str(response.content)
